services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  IchHabRecht\Upgrader\Command\UpgradeCommand:
    tags:
      - name: 'console.command'
        command: 'coreupgrader:upgrade'
        description: 'Clears the opcode cache'
